Btn profile name, register, user profile bug fixes from dev branch
aastarurmika/eagle-fusion pull request #46
Opened 2021-03-16 14:14 UTC by revathip

2021-03-17 05:03 UTC, aastarurmika requested changes

2021-03-17 05:03 UTC, aastarurmika commented on library/ws-widget/collection/src/lib/btn-profile/btn-profile.component.html
> +  <span class="padding-left-xs" i18n>{{ name || 'Guest'}} </span>
@revathip

2021-03-17 05:03 UTC, aastarurmika commented on src/app/routes/forgot-password/forgot-password.component.ts
> +            this.openSnackbar('User data doesnot exist')
@revathip

2021-03-17 05:03 UTC, aastarurmika commented on src/app/routes/forgot-password/forgot-password.component.ts
> +            this.openSnackbar(error.error.error)
@revathip

2021-03-17 15:01 UTC, revathip commented
@ankitv89 , review comments are completed.

2021-04-07 04:39 UTC, ankitv89 commented
@revathip do we still need to merge this PR or can we close this?

2021-04-12 05:56 UTC, closed without merging

2021-04-12 05:57 UTC, revathip commented
Feature is already pushed and deployed